spring.application.name=Crud Spring React
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always

management.endpoints.web.exposure.include=health,info